//! Auto-classification — detect file roles, test status, and stability
//! using tree-sitter AST queries. No LLM required.
//!
//! Reference: `tree-sitter-analyzer` (PyPI, MIT) — 13-language call-graph
//! indexing with per-language resolvers for entrypoint/test/library detection.

use crate::error::GraphResult;
use crate::parser::Language;
use crate::signal::extract_rust_name;
use tree_sitter::Parser as TsParser;

/// Classification labels written as xattrs (user.vfs.*).
#[derive(Debug, Clone, PartialEq)]
pub struct Classification {
    /// "entrypoint", "library", "test", "example", "config", "script",
    /// "build", "generated", "unknown"
    pub role: String,
    /// "stable", "beta", "unstable", "deprecated", "unknown"
    pub status: String,
    /// Human-readable reason for the classification.
    pub reason: String,
    /// Inferred feature name (e.g., "auth-module") — set via `infer_feature()`.
    pub feature: Option<String>,
}

/// Generated file header markers from spec §4 discovery.generated_detection.
const GENERATED_HEADER_MARKERS: &[&str] = &["DO NOT EDIT", "auto-generated", "Code generated by"];

/// Generated file path patterns from spec §4 discovery.generated_detection.
const GENERATED_PATH_PATTERNS: &[&str] = &[".pb.go", ".gen.go", ".generated."];

/// Check if a file is auto-generated by header markers or path patterns.
///
/// Path markers check the filename (e.g., `*.pb.go`, `*.gen.go`, `*.generated.*`).
/// Header markers check the first ~200 bytes of file content.
/// Either is sufficient to classify as generated.
pub fn is_generated_file(path: &str, first_bytes: &[u8]) -> bool {
    // Path-based detection (fast, no content needed)
    for pattern in GENERATED_PATH_PATTERNS {
        if path.contains(pattern) {
            return true;
        }
    }

    // Header-based detection
    let header = String::from_utf8_lossy(first_bytes);
    for marker in GENERATED_HEADER_MARKERS {
        if header.contains(marker) {
            return true;
        }
    }

    false
}

/// Classify a source file by language, filename, and content.
pub fn classify_file(
    language: Language,
    file_path: &str,
    source: &str,
) -> GraphResult<Classification> {
    // 0. Generated file detection (before any other classification —
    //    generated files should not be treated as test/library/entrypoint)
    if is_generated_file(file_path, source.as_bytes()) {
        return Ok(Classification {
            role: "generated".into(),
            status: "generated".into(),
            reason: "matches generated file pattern (header or path marker)".into(),
            feature: None,
        });
    }

    // 1. Test detection by filename pattern (fastest, no parsing needed)
    if is_test_file(file_path) {
        return Ok(Classification {
            role: "test".into(),
            status: classify_test_status(file_path),
            reason: format!("filename matches test pattern for {:?}", language),
            feature: None,
        });
    }

    // 2. Build script detection by filename convention (build.rs contains
    //    `fn main()` and would otherwise be caught by the AST entrypoint
    //    check below — build scripts are NOT application entrypoints)
    if is_build_script(file_path) {
        return Ok(Classification {
            role: "build".into(),
            status: "stable".into(),
            reason: "build script (filename convention)".into(),
            feature: None,
        });
    }

    // 3. Entrypoint detection by filename convention
    if is_entrypoint_by_name(file_path) {
        return Ok(Classification {
            role: "entrypoint".into(),
            status: "stable".into(),
            reason: format!("filename convention: {:?}", language),
            feature: None,
        });
    }

    // 4. Crate/module root convention: lib.rs is the library crate root;
    //    mod.rs is a module root (src/mod.rs = crate root module, nested
    //    dirs = module roots). Both are library surface, never entrypoints —
    //    even when they contain few `pub fn` items (macro/re-export walls
    //    like serde's lib.rs would otherwise fall through to "unknown").
    if is_crate_module_root(file_path) {
        return Ok(Classification {
            role: "library".into(),
            status: classify_library_status(file_path),
            reason: "crate/module root convention (lib.rs/mod.rs)".into(),
            feature: None,
        });
    }

    // 5. AST-based detection for main functions and library markers
    let mut parser = TsParser::new();
    let ts_lang = language_to_ts(language);
    parser
        .set_language(&ts_lang)
        .map_err(|e| crate::error::GraphError::Other(format!("failed to set language: {e}")))?;

    let tree = parser.parse(source.as_bytes(), None).ok_or_else(|| {
        crate::error::GraphError::Other("tree-sitter produced no parse tree".into())
    })?;

    let root = tree.root_node();

    // Check for main/entrypoint patterns
    if has_entrypoint(root, source.as_bytes(), language) {
        return Ok(Classification {
            role: "entrypoint".into(),
            status: "stable".into(),
            reason: format!("contains entrypoint pattern for {:?}", language),
            feature: None,
        });
    }

    // 5b. Canonical entry symbols (GAP-099): frameworks expose their
    // "where do I start" surface as canonical named symbols rather than a
    // main function — Go constructor sets (New/Default/Run, e.g. gin.go)
    // and Python application classes (class Flask). A file declaring them
    // is an entrypoint even though it also carries library surface.
    if has_canonical_entry(root, source.as_bytes(), language) {
        return Ok(Classification {
            role: "entrypoint".into(),
            status: "stable".into(),
            reason: format!("declares canonical entry symbols for {:?}", language),
            feature: None,
        });
    }

    // Check for public API surface (library markers)
    if has_public_api(root, source.as_bytes(), language) {
        return Ok(Classification {
            role: "library".into(),
            status: classify_library_status(file_path),
            reason: format!("has public API surface for {:?}", language),
            feature: None,
        });
    }

    // Fallback: classify by directory convention
    classify_by_path(file_path)
}

// ── Language to tree-sitter ─────────────────────────────────────────

fn language_to_ts(lang: Language) -> tree_sitter::Language {
    match lang {
        Language::Go => tree_sitter_go::LANGUAGE.into(),
        Language::Python => tree_sitter_python::LANGUAGE.into(),
        Language::TypeScript => tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
        Language::Rust => tree_sitter_rust::LANGUAGE.into(),
        Language::JavaScript => tree_sitter_javascript::LANGUAGE.into(),
        Language::Java => tree_sitter_java::LANGUAGE.into(),
        Language::C => tree_sitter_c::LANGUAGE.into(),
        Language::Cpp => tree_sitter_cpp::LANGUAGE.into(),
        Language::Ruby => tree_sitter_ruby::LANGUAGE.into(),
        Language::CSharp => tree_sitter_c_sharp::LANGUAGE.into(),
        Language::Kotlin => tree_sitter_kotlin_ng::LANGUAGE.into(),
        Language::Php => tree_sitter_php::LANGUAGE_PHP.into(),
        Language::Swift => tree_sitter_swift::LANGUAGE.into(),
        Language::Elixir => tree_sitter_elixir::LANGUAGE.into(),
        Language::Haskell => tree_sitter_haskell::LANGUAGE.into(),
        Language::Erlang => tree_sitter_erlang::LANGUAGE.into(),
        Language::Scala => tree_sitter_scala::LANGUAGE.into(),
        Language::Zig => tree_sitter_zig::LANGUAGE.into(),
        Language::Lua => tree_sitter_lua::LANGUAGE.into(),
        Language::Dart => tree_sitter_dart::LANGUAGE.into(),
        Language::Clojure => tree_sitter_clojure::LANGUAGE.into(),
        Language::OCaml => tree_sitter_ocaml::LANGUAGE_OCAML.into(),
        Language::R => tree_sitter_r::LANGUAGE.into(),
        Language::Julia => tree_sitter_julia::LANGUAGE.into(),
        Language::Elm => tree_sitter_elm::LANGUAGE.into(),
        Language::Nim => tree_sitter_nim::language(),
    }
}

/// Per-language source-text seeds for AST-detected entrypoints.
///
/// When a file becomes role=entrypoint via its language's `has_*_main`
/// pattern (not the filename convention), the callable an agent starts at
/// is described by this source text rather than a single symbol name —
/// e.g. Python's `if __name__ == "__main__":` guard, Go's `func main()`.
/// GAP-099 renders this verbatim so `hilo classify` answers "where does
/// execution start" even when the entrypoint is a pattern, not a symbol.
/// Each seed matches the corresponding `has_*_entrypoint` detector.
fn entrypoint_source_seeds(language: Language) -> &'static [&'static str] {
    match language {
        // Existing AST-detection text patterns, kept as source here (no
        // behavior change — the same strings classify the file, they now
        // also seed the symbol report):
        Language::Python => &["if __name__ == \"__main__\"", "if __name__ == '__main__'"],
        Language::Go => &["func main()"],
        Language::Java => &["public static void main("],
        Language::Rust => &["fn main("],
        Language::C | Language::Cpp => &["int main", "void main"],
        Language::Scala => &["def main(", "@main"],
        Language::Zig => &["pub fn main("],
        Language::CSharp => &["static void Main(", "static async Task Main("],
        Language::Kotlin => &["fun main("],
        Language::Elixir => &["def main("],
        Language::Haskell => &["main"], // detector: any trimmed line start
        Language::Erlang => &["-module(main)"],
        Language::Julia => &["function main("],
        Language::Dart => &["main()", "main(List"],
        Language::Clojure => &["(-main"],
        // Detectors for these languages are pure AST or shebang checks with
        // no single text marker:
        Language::JavaScript
        | Language::TypeScript
        | Language::Ruby
        | Language::Php
        | Language::Swift
        | Language::Lua
        | Language::OCaml
        | Language::R
        | Language::Elm
        | Language::Nim => &[],
    }
}

/// The symbol report line for one entrypoint file (GAP-099):
/// names of the file's top-level entry symbols — the callables an agent
/// starts at. Files whose entrypoint is a source pattern rather than a
/// named symbol (Go's `func main()`, Python's `if __name__ == "__main__"`
/// guard) carry a seed-string marker in angle brackets instead, and
/// wrapper-style entrypoints (flask's `cli.py`: `if __name__ == "__main__"`
/// around `main()`) surface the wrapper's target: the first top-level
/// symbol whose definition line follows the last entrypoint-seed line.
pub fn entry_symbols_for_classification(
    language: Language,
    reason: &str,
    source: &str,
) -> Vec<String> {
    let mut symbols = extract_entry_symbols(language, source);

    let by_convention = reason.starts_with("filename convention");
    let seed_for_marker = if by_convention {
        None
    } else {
        entrypoint_source_seeds(language)
            .iter()
            .find(|seed| source.contains(*seed))
    };

    match seed_for_marker {
        // A seed matched: this file's entrypoint is that pattern, not a
        // named symbol. Keep only symbols the pattern's line can reach —
        // either defined after it, or named in its body (a wrapper like
        // flask cli.py's `if __name__ == "__main__": main()`).
        Some(seed) => {
            let seed_end = source.find(seed).map(|i| i + seed.len()).unwrap_or(0);
            let seed_line = source[..seed_end].matches('\n').count() + 1;
            filter_symbols_after_line(&mut symbols, language, source, seed_line);
            if !has_symbol_marker(&symbols) {
                // Wrapper target: a symbol named inside the guard's body.
                if let Some(target) = wrapper_target_after_seed(language, source, seed_end) {
                    if !symbols.contains(&target) {
                        symbols.push(target);
                    }
                }
            }
            if !has_symbol_marker(&symbols) {
                symbols.push(format!("<{seed}>"));
            }
            symbols
        }
        // By-convention entrypoints (main.rs, __main__.py) report their
        // symbols as-is; files with no symbols get no line at all.
        None => symbols,
    }
}

/// The first symbol defined anywhere in the file whose name appears in the
/// source text after `offset` — i.e. the callable a pattern-entrypoint's
/// body invokes (flask cli.py: `main` defined before the guard, invoked
/// inside it). Python call shape `name(`, Go call shape `name(`.
fn wrapper_target_after_seed(language: Language, source: &str, offset: usize) -> Option<String> {
    let tail = &source[offset.min(source.len())..];
    let defined = definition_lines(language, source);
    // Prefer the definition closest to the tail's first word boundary hit.
    let mut best: Option<(usize, String)> = None;
    for (name, _line) in &defined {
        let needle = format!("{name}(");
        if let Some(pos) = tail.find(&needle) {
            if best.as_ref().map(|(p, _)| pos < *p).unwrap_or(true) {
                best = Some((pos, name.clone()));
            }
        }
    }
    best.map(|(_, n)| n)
}

/// Marker shape used for pattern-entrypoints (`<func main()>`).
fn has_symbol_marker(symbols: &[String]) -> bool {
    symbols
        .iter()
        .any(|s| s.starts_with('<') && s.ends_with('>'))
}

/// Keep only symbols defined after `line` (the entrypoint guard's line) —
/// used when a pattern seeds the entrypoint so wrapper targets like
/// flask cli.py's `main()` (defined after `if __name__ == "__main__":`
/// via the click group) surface. Python defs/classes map line→name via
/// the AST; the definition node's start row must be >= the guard line.
fn filter_symbols_after_line(
    symbols: &mut Vec<String>,
    language: Language,
    source: &str,
    line: usize,
) {
    if line == 0 {
        return;
    }
    let lines_with_defs = definition_lines(language, source);
    symbols.retain(|s| lines_with_defs.iter().any(|(n, l)| n == s && *l >= line));
}

/// (name, 1-based start line) of every definition in a file that the
/// entry-symbol walkers count — the line map `filter_symbols_after_line`
/// filters against. Covers Python (defs/classes), Go (func decls and
/// methods) and Rust (function items) so a pattern seed in any of the
/// three entry-symbol languages can keep the symbols defined after it.
fn definition_lines(language: Language, source: &str) -> Vec<(String, usize)> {
    let mut parser = TsParser::new();
    if parser.set_language(&language_to_ts(language)).is_err() {
        return Vec::new();
    }
    let Some(tree) = parser.parse(source.as_bytes(), None) else {
        return Vec::new();
    };
    let src = source.as_bytes();
    let mut out = Vec::new();
    def_lines_walk(tree.root_node(), src, language, &mut out);
    out
}

fn def_lines_walk(
    node: tree_sitter::Node,
    source: &[u8],
    language: Language,
    out: &mut Vec<(String, usize)>,
) {
    let kind = node.kind();
    let is_def = match language {
        Language::Python => matches!(kind, "function_definition" | "class_definition"),
        Language::Go => matches!(kind, "function_declaration" | "method_declaration"),
        Language::Rust => kind == "function_item",
        _ => false,
    };
    if is_def {
        if let Some(name) = node
            .child_by_field_name("name")
            .and_then(|n| n.utf8_text(source).ok())
        {
            out.push((name.to_string(), node.start_position().row + 1));
            return; // nested defs are not top-level
        }
    }
    let mut cursor = node.walk();
    let children: Vec<tree_sitter::Node> = node.children(&mut cursor).collect();
    for child in children {
        def_lines_walk(child, source, language, out);
    }
}

// ── Entry symbols (GAP-099) ─────────────────────────────────────────

/// Maximum entry symbols listed per file before a "... N more" tail.
pub const ENTRY_SYMBOLS_CAP: usize = 10;

/// Entry-symbol definition, per language:
/// - Rust: top-level `pub` fns (plus `fn main`).
/// - Python: top-level def/class names (Flask = the class).
///
/// Go = top-level func decls, exported ones first; canonical entry names
/// (New/Default/Run) lead the exported band, and exported top-level
/// methods (e.g. `func (e *Engine) Run(...)` in gin.go — a framework's
/// actual "where do I start" surface, which has no `func main`) count.
///
/// Unsupported languages yield an empty list (no line is printed).
pub fn extract_entry_symbols(language: Language, source: &str) -> Vec<String> {
    let mut parser = TsParser::new();
    if parser.set_language(&language_to_ts(language)).is_err() {
        return Vec::new();
    }
    let Some(tree) = parser.parse(source.as_bytes(), None) else {
        return Vec::new();
    };

    let source = source.as_bytes();
    let root = tree.root_node();

    match language {
        Language::Rust => rust_entry_symbols(root, source),
        Language::Python => python_entry_symbols(root, source),
        Language::Go => go_entry_symbols(root, source),
        _ => Vec::new(),
    }
}

/// True when a Rust item sits directly in the file's top-level item list
/// (its parent is `source_file`; tree-sitter-rust attaches attributes as
/// preceding siblings, so no attribute unwrapping is needed). Checking the
/// immediate parent — not the whole ancestor chain — is the point: every
/// chain eventually reaches `source_file`, so a chain walk would accept
/// `impl`-block and nested functions too.
fn is_top_level_rust(node: tree_sitter::Node) -> bool {
    node.parent().is_some_and(|p| p.kind() == "source_file")
}

/// A Rust definition's name, when the definition is public.
/// `extract_rust_name` (signal.rs, reused) already skips pub/async/unsafe;
/// visibility is decided from the node's own first line so private items
/// (`fn helper()` — no `pub`) never become entry symbols.
fn rust_entry_symbol_name(node: tree_sitter::Node, source: &[u8]) -> Option<String> {
    let text = node.utf8_text(source).unwrap_or("");
    let first = text.lines().next().unwrap_or(text).trim();
    let is_public = first.starts_with("pub ")
        || (node.kind() == "function_item" && first.starts_with("fn main("));
    if !is_public {
        return None;
    }
    extract_rust_name(first)
}

/// Rust = top-level pub fns (plus `fn main`), in source order.
fn rust_entry_symbols(root: tree_sitter::Node, source: &[u8]) -> Vec<String> {
    let mut names = Vec::new();
    rust_entry_walk(root, source, &mut names);
    names
}

fn rust_entry_walk(node: tree_sitter::Node, source: &[u8], names: &mut Vec<String>) {
    if node.kind() == "function_item" && is_top_level_rust(node) {
        if let Some(name) = rust_entry_symbol_name(node, source) {
            if !names.contains(&name) {
                names.push(name);
            }
        }
    }
    let mut cursor = node.walk();
    let children: Vec<tree_sitter::Node> = node.children(&mut cursor).collect();
    for child in children {
        rust_entry_walk(child, source, names);
    }
}

/// Python = top-level def/class names, in source order.
fn python_entry_symbols(root: tree_sitter::Node, source: &[u8]) -> Vec<String> {
    let mut names = Vec::new();
    python_entry_walk(root, source, &mut names);
    names
}

fn python_entry_walk(node: tree_sitter::Node, source: &[u8], names: &mut Vec<String>) {
    match node.kind() {
        "function_definition" | "class_definition" => {
            if let Some(name) = node.child_by_field_name("name") {
                if let Ok(n) = name.utf8_text(source) {
                    if !n.is_empty() && !names.contains(&n.to_string()) {
                        names.push(n.to_string());
                    }
                }
            }
            // Do NOT descend: nested defs/classes are not top-level entries.
            return;
        }
        _ => {}
    }
    let mut cursor = node.walk();
    let children: Vec<tree_sitter::Node> = node.children(&mut cursor).collect();
    for child in children {
        python_entry_walk(child, source, names);
    }
}

/// Go = top-level func decls and methods, exported ones first.
/// Order: canonical entry names (New/Default/Run) → other exported
/// (Capitalized) names in source order → unexported names in source order.
fn go_entry_symbols(root: tree_sitter::Node, source: &[u8]) -> Vec<String> {
    let mut plain: Vec<String> = Vec::new();
    let mut exported: Vec<String> = Vec::new();
    go_entry_walk(root, source, &mut plain, &mut exported);

    let canonical: &[&str] = &["New", "Default", "Run"];
    let mut names: Vec<String> = Vec::new();
    for c in canonical {
        if exported.iter().any(|n| n == c) {
            names.push((*c).to_string());
        }
    }
    for n in exported {
        if !names.contains(&n) {
            names.push(n);
        }
    }
    for n in plain {
        if !names.contains(&n) {
            names.push(n);
        }
    }
    names
}

fn go_entry_walk(
    node: tree_sitter::Node,
    source: &[u8],
    plain: &mut Vec<String>,
    exported: &mut Vec<String>,
) {
    if node.kind() == "function_declaration" || node.kind() == "method_declaration" {
        if let Some(name_node) = node.child_by_field_name("name") {
            if let Ok(n) = name_node.utf8_text(source) {
                if !n.is_empty() {
                    let name = n.to_string();
                    let is_exported = n.chars().next().is_some_and(|c| c.is_uppercase());
                    if is_exported {
                        if !exported.contains(&name) {
                            exported.push(name);
                        }
                    } else if !plain.contains(&name) {
                        plain.push(name);
                    }
                }
            }
        }
        return; // top-level only: a func/method body is not a nested decl candidate
    }
    let mut cursor = node.walk();
    let children: Vec<tree_sitter::Node> = node.children(&mut cursor).collect();
    for child in children {
        go_entry_walk(child, source, plain, exported);
    }
}

// ── Test file detection ─────────────────────────────────────────────

/// Depth-agnostic test/bench directory check — any path component equal to
/// `test`, `tests`, `benches`, or `__tests__` marks a test/bench file,
/// whether top-level (`tests/foo.rs`) or nested (`crates/*/tests/`).
/// Component equality (not substring) avoids false positives like
/// `src/test_utils/` or `mytests/`.
fn is_test_dir_component(comp: &str) -> bool {
    matches!(comp, "test" | "tests" | "benches" | "__tests__")
}

pub(crate) fn is_test_file(path: &str) -> bool {
    let lower = path.to_lowercase();
    // Universal test patterns
    if lower.contains("_test.") || lower.contains(".test.") || lower.contains("_spec.") {
        return true;
    }
    if lower.starts_with("test_") || lower.ends_with("_test.go") {
        return true;
    }
    // Directory-based detection — depth-agnostic: top-level `tests/` and
    // `benches/` (no leading slash) are matched exactly like nested
    // `crates/*/tests/`, across both `/` and `\` path separators.
    if lower.split(['/', '\\']).any(is_test_dir_component) {
        return true;
    }
    // Language-specific
    if lower.ends_with("test.java") || lower.ends_with("tests.java") {
        return true;
    }
    if lower.ends_with("_spec.rb") {
        return true;
    }
    // C#: *Test.cs, *Tests.cs
    if lower.ends_with("test.cs") || lower.ends_with("tests.cs") {
        return true;
    }
    // Kotlin: *Test.kt, *Tests.kt
    if lower.ends_with("test.kt") || lower.ends_with("tests.kt") {
        return true;
    }
    // PHP: *Test.php, *Tests.php
    if lower.ends_with("test.php") || lower.ends_with("tests.php") {
        return true;
    }
    // Swift: *Test.swift, *Tests.swift
    if lower.ends_with("test.swift") || lower.ends_with("tests.swift") {
        return true;
    }
    // Elixir: *_test.exs, test_*.exs
    if lower.ends_with("_test.exs") || lower.ends_with(".test.exs") {
        return true;
    }
    if lower.starts_with("test_") && (lower.ends_with(".ex") || lower.ends_with(".exs")) {
        return true;
    }
    // Haskell: *Spec.hs, *Test.hs
    if lower.ends_with("spec.hs") || lower.ends_with("test.hs") || lower.ends_with("tests.hs") {
        return true;
    }
    // Erlang: *_SUITE.erl (Common Test suites)
    if lower.ends_with("_suite.erl") {
        return true;
    }
    // Scala: *Test.scala, *Tests.scala, *Spec.scala
    if lower.ends_with("test.scala")
        || lower.ends_with("tests.scala")
        || lower.ends_with("spec.scala")
    {
        return true;
    }
    // Zig: *_test.zig, test.zig
    if lower.ends_with("_test.zig") || lower.ends_with(".test.zig") {
        return true;
    }
    // Lua: _test.lua, _spec.lua, test_*.lua
    if lower.ends_with("_test.lua") || lower.ends_with("_spec.lua") || lower.ends_with(".test.lua")
    {
        return true;
    }
    if lower.starts_with("test_") && lower.ends_with(".lua") {
        return true;
    }
    // Dart: *_test.dart, test_*.dart
    if lower.ends_with("_test.dart") || lower.ends_with(".test.dart") {
        return true;
    }
    // Clojure: *_test.clj, test_*.clj, *_test.cljs
    if lower.ends_with("_test.clj") || lower.ends_with(".test.clj") || lower.ends_with("_test.cljs")
    {
        return true;
    }
    if lower.starts_with("test_") && (lower.ends_with(".clj") || lower.ends_with(".cljs")) {
        return true;
    }
    // OCaml: *_test.ml, test_*.ml, *_test.mli
    if lower.ends_with("_test.ml") || lower.ends_with(".test.ml") || lower.ends_with("_test.mli") {
        return true;
    }
    // R: test-*.R, test_*.R
    if lower.starts_with("test-") && lower.ends_with(".r") {
        return true;
    }
    if lower.starts_with("test_") && lower.ends_with(".r") {
        return true;
    }
    // Julia: *_test.jl, test_*.jl, runtests.jl
    if lower.ends_with("_test.jl") || lower.ends_with(".test.jl") {
        return true;
    }
    if lower.starts_with("test_") && lower.ends_with(".jl") {
        return true;
    }
    if lower.ends_with("runtests.jl") {
        return true;
    }
    // Elm: *Test.elm, *Tests.elm
    if lower.ends_with("test.elm") || lower.ends_with("tests.elm") {
        return true;
    }
    // Nim: *_test.nim, test_*.nim
    if lower.ends_with("_test.nim") || lower.ends_with(".test.nim") {
        return true;
    }
    if lower.starts_with("test_") && lower.ends_with(".nim") {
        return true;
    }
    // __test__ directories (Python convention)
    if lower.contains("__test__") {
        return true;
    }
    false
}

fn classify_test_status(_path: &str) -> String {
    // Test files are inherently less stable than production code
    "beta".into()
}

// ── Build script detection ──────────────────────────────────────────

/// Build scripts (build.rs for Cargo, build.zig for Zig) run at compile
/// time and contain `fn main()` — they must never be classified as
/// application entrypoints.
fn is_build_script(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.ends_with("build.rs") || lower.ends_with("build.zig")
}

// ── Crate/module root detection ─────────────────────────────────────

/// `lib.rs` = library crate root; `mod.rs` = module root (either the
/// crate-root module `src/mod.rs` or a nested `src/foo/mod.rs`). Both are
/// library surface and never entrypoint files.
fn is_crate_module_root(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.ends_with("lib.rs") || lower.ends_with("mod.rs")
}

// ── Entrypoint detection by filename ────────────────────────────────

fn is_entrypoint_by_name(path: &str) -> bool {
    let lower = path.to_lowercase();
    // main.rs, main.go, main.py, Main.java, main.c, main.cpp, etc.
    if lower.ends_with("main.rs")
        || lower.ends_with("main.go")
        || lower.ends_with("main.py")
        || lower.ends_with("main.c")
        || lower.ends_with("main.cpp")
        || lower.ends_with("main.js")
        || lower.ends_with("main.ts")
        || lower.ends_with("main.rb")
    {
        return true;
    }
    // index.js, index.ts (Node.js entrypoint convention)
    if lower.ends_with("index.js") || lower.ends_with("index.ts") {
        return true;
    }
    // __main__.py (Python package entrypoint)
    if lower.ends_with("__main__.py") {
        return true;
    }
    // C#: Program.cs (default entrypoint)
    if lower.ends_with("program.cs") {
        return true;
    }
    // Kotlin: Main.kt (default entrypoint)
    if lower.ends_with("main.kt") {
        return true;
    }
    // PHP: index.php (web entrypoint)
    if lower.ends_with("index.php") {
        return true;
    }
    // Swift: main.swift (command-line entrypoint)
    if lower.ends_with("main.swift") {
        return true;
    }
    // Elixir: myapp.exs, mix.exs, application.ex
    if lower.ends_with("mix.exs") || lower.ends_with("application.ex") {
        return true;
    }
    // Haskell: Main.hs
    if lower.ends_with("main.hs") || lower.ends_with("main.lhs") {
        return true;
    }
    // Erlang: escript, main.erl
    if lower.ends_with("escript.erl") || lower.ends_with("main.erl") {
        return true;
    }
    // Scala: Main.scala, App.scala
    if lower.ends_with("main.scala") || lower.ends_with("app.scala") {
        return true;
    }
    // Zig: main.zig
    if lower.ends_with("main.zig") {
        return true;
    }
    // Lua: main.lua, init.lua
    if lower.ends_with("main.lua") || lower.ends_with("init.lua") {
        return true;
    }
    // Dart: main.dart, index.dart
    if lower.ends_with("main.dart") {
        return true;
    }
    // Clojure: core.clj, main.clj
    if lower.ends_with("core.clj") || lower.ends_with("main.clj") {
        return true;
    }
    // OCaml: main.ml
    if lower.ends_with("main.ml") {
        return true;
    }
    // R: main.R
    if lower.ends_with("main.r") {
        return true;
    }
    // Julia: main.jl
    if lower.ends_with("main.jl") {
        return true;
    }
    // Elm: Main.elm
    if lower.ends_with("main.elm") {
        return true;
    }
    // Nim: main.nim
    if lower.ends_with("main.nim") {
        return true;
    }
    false
}

// ── AST-based entrypoint detection ──────────────────────────────────

fn has_entrypoint(node: tree_sitter::Node, source: &[u8], language: Language) -> bool {
    match language {
        Language::Rust => has_rust_main(node, source),
        Language::Python => has_python_main(node, source),
        Language::Go => has_go_main(node, source),
        Language::JavaScript | Language::TypeScript => has_js_entrypoint(node, source),
        Language::Java => has_java_main(node, source),
        Language::C | Language::Cpp => has_c_main(node, source),
        Language::Ruby => has_ruby_entrypoint(node, source),
        Language::CSharp => has_csharp_main(node, source),
        Language::Kotlin => has_kotlin_main(node, source),
        Language::Php => has_php_entrypoint(node, source),
        Language::Swift => has_swift_entrypoint(node, source),
        Language::Elixir => has_elixir_entrypoint(node, source),
        Language::Haskell => has_haskell_entrypoint(node, source),
        Language::Erlang => has_erlang_entrypoint(node, source),
        Language::Scala => has_scala_entrypoint(node, source),
        Language::Zig => has_zig_entrypoint(node, source),
        Language::Lua => has_lua_entrypoint(node, source),
        Language::Dart => has_dart_entrypoint(node, source),
        Language::Clojure => has_clojure_entrypoint(node, source),
        Language::OCaml => has_ocaml_entrypoint(node, source),
        Language::R => has_r_entrypoint(node, source),
        Language::Julia => has_julia_entrypoint(node, source),
        Language::Elm => has_elm_entrypoint(node, source),
        Language::Nim => has_nim_entrypoint(node, source),
    }
}

fn has_rust_main(node: tree_sitter::Node, source: &[u8]) -> bool {
    if node.kind() == "function_item" {
        let text = node.utf8_text(source).unwrap_or("");
        return text.starts_with("fn main(");
    }
    walk_children(node, source, has_rust_main)
}

fn has_python_main(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("if __name__ == \"__main__\"") || text.contains("if __name__ == '__main__'") {
        return true;
    }
    walk_children(node, source, has_python_main)
}

fn has_go_main(node: tree_sitter::Node, source: &[u8]) -> bool {
    if node.kind() == "function_declaration" {
        let text = node.utf8_text(source).unwrap_or("");
        return text.contains("func main()");
    }
    walk_children(node, source, has_go_main)
}

// ── Canonical entry symbols (GAP-099) ───────────────────────────────

/// Go constructor names that form a framework's entry surface. gin.go is
/// the reference corpus: `func New()`, `func Default()` and the
/// `func (e *Engine) Run(...)` method together are "where execution
/// starts"; no single one of them is (a lone `func New()` is a common
/// plain constructor).
const CANONICAL_GO_ENTRY_NAMES: &[&str] = &["New", "Default", "Run"];

/// Python application classes whose instantiation is where an application
/// starts (the flask corpus's `class Flask`). Extensible list.
const CANONICAL_PYTHON_ENTRY_CLASSES: &[&str] = &["Flask"];

/// True when the file declares at least two distinct canonical Go entry
/// names as top-level func declarations or methods.
fn has_canonical_go_entry(node: tree_sitter::Node, source: &[u8]) -> bool {
    canonical_go_entry_names(node, source).len() >= 2
}

/// The canonical Go entry names present as (top-level) func declarations
/// or methods. Go cannot nest function declarations, so a full walk only
/// ever sees file-scope decls.
fn canonical_go_entry_names(node: tree_sitter::Node, source: &[u8]) -> Vec<&'static str> {
    let mut out: Vec<&'static str> = Vec::new();
    if node.kind() == "function_declaration" || node.kind() == "method_declaration" {
        if let Some(name) = node
            .child_by_field_name("name")
            .and_then(|n| n.utf8_text(source).ok())
        {
            if let Some(c) = CANONICAL_GO_ENTRY_NAMES.iter().find(|c| **c == name) {
                out.push(c);
            }
        }
        return out;
    }
    let mut cursor = node.walk();
    let children: Vec<tree_sitter::Node> = node.children(&mut cursor).collect();
    for child in children {
        for name in canonical_go_entry_names(child, source) {
            if !out.contains(&name) {
                out.push(name);
            }
        }
    }
    out
}

/// True when a class named in CANONICAL_PYTHON_ENTRY_CLASSES is declared
/// at the file's top level.
fn has_canonical_python_entry(node: tree_sitter::Node, source: &[u8]) -> bool {
    if node.kind() == "class_definition" {
        if let Some(name) = node
            .child_by_field_name("name")
            .and_then(|n| n.utf8_text(source).ok())
        {
            return CANONICAL_PYTHON_ENTRY_CLASSES.contains(&name);
        }
        return false;
    }
    let mut cursor = node.walk();
    let children: Vec<tree_sitter::Node> = node.children(&mut cursor).collect();
    children
        .into_iter()
        .any(|c| has_canonical_python_entry(c, source))
}

/// Language dispatch for canonical-entry-symbol detection (GAP-099).
/// Languages without a canonical-symbol entry convention return false.
fn has_canonical_entry(node: tree_sitter::Node, source: &[u8], language: Language) -> bool {
    match language {
        Language::Go => has_canonical_go_entry(node, source),
        Language::Python => has_canonical_python_entry(node, source),
        _ => false,
    }
}

fn has_js_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    // module.exports =, export default function, or direct script entry
    if text.contains("module.exports")
        || text.contains("export default")
        || text.contains("exports.")
    {
        return true;
    }
    walk_children(node, source, has_js_entrypoint)
}

fn has_java_main(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("public static void main(") {
        return true;
    }
    walk_children(node, source, has_java_main)
}

fn has_c_main(node: tree_sitter::Node, source: &[u8]) -> bool {
    if node.kind() == "function_definition" {
        let text = node.utf8_text(source).unwrap_or("");
        return text.contains("main(") && (text.contains("int main") || text.contains("void main"));
    }
    walk_children(node, source, has_c_main)
}

fn has_ruby_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    // Ruby scripts often start with #!/usr/bin/env ruby or have top-level calls
    if text.starts_with("#!/usr/bin/env ruby") {
        return true;
    }
    walk_children(node, source, has_ruby_entrypoint)
}

fn has_csharp_main(node: tree_sitter::Node, source: &[u8]) -> bool {
    if node.kind() == "method_declaration" {
        let text = node.utf8_text(source).unwrap_or("");
        if text.contains("static void Main(") || text.contains("static async Task Main(") {
            return true;
        }
    }
    walk_children(node, source, has_csharp_main)
}

fn has_kotlin_main(node: tree_sitter::Node, source: &[u8]) -> bool {
    if node.kind() == "function_declaration" {
        let text = node.utf8_text(source).unwrap_or("");
        if text.starts_with("fun main(") {
            return true;
        }
    }
    walk_children(node, source, has_kotlin_main)
}

fn has_php_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    // PHP CLI scripts have shebang or top-level execution
    if text.starts_with("#!/usr/bin/env php") || text.starts_with("#!/usr/bin/php") {
        return true;
    }
    walk_children(node, source, has_php_entrypoint)
}

fn has_swift_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Swift uses @main attribute or @UIApplicationMain / @NSApplicationMain
    if node.kind() == "attribute" {
        let text = node.utf8_text(source).unwrap_or("");
        if text == "@main" || text == "@UIApplicationMain" || text == "@NSApplicationMain" {
            return true;
        }
    }
    walk_children(node, source, has_swift_entrypoint)
}

fn has_elixir_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Elixir scripts often start with shebang or have a top-level `main/0` def
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("def main(") || text.starts_with("#!") {
        return true;
    }
    walk_children(node, source, has_elixir_entrypoint)
}

fn has_haskell_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // `main =` is the entrypoint in Haskell
    let text = node.utf8_text(source).unwrap_or("");
    if text
        .lines()
        .any(|l| l.trim().starts_with("main") || l.trim().starts_with("main ="))
    {
        return true;
    }
    walk_children(node, source, has_haskell_entrypoint)
}

fn has_erlang_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // `-module(main).` or scripts with `-module(escript)` / shebang
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("-module(main)") || text.starts_with("#!") {
        return true;
    }
    walk_children(node, source, has_erlang_entrypoint)
}

fn has_scala_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // `def main(args: Array[String]): Unit =` or `@main def myApp() =`
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("def main(") || text.contains("@main") {
        return true;
    }
    // Scala 3: extends App trait
    if text.contains("extends App") {
        return true;
    }
    walk_children(node, source, has_scala_entrypoint)
}

fn has_zig_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // `pub fn main()` is the entrypoint
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("pub fn main(") {
        return true;
    }
    walk_children(node, source, has_zig_entrypoint)
}

fn has_lua_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Lua scripts often have shebang or top-level calls
    let text = node.utf8_text(source).unwrap_or("");
    if text.starts_with("#!") {
        return true;
    }
    walk_children(node, source, has_lua_entrypoint)
}

fn has_dart_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // `void main()` or `main()` function declaration
    if node.kind() == "function_declaration" || node.kind() == "function_signature" {
        let text = node.utf8_text(source).unwrap_or("");
        if text.contains("main()") || text.contains("main(List") {
            return true;
        }
    }
    walk_children(node, source, has_dart_entrypoint)
}

fn has_clojure_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Clojure: `(-main & args)` function or shebang
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("(-main") || text.starts_with("#!") {
        return true;
    }
    walk_children(node, source, has_clojure_entrypoint)
}

fn has_ocaml_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // OCaml: no standard main function, but scripts may have shebang
    let text = node.utf8_text(source).unwrap_or("");
    if text.starts_with("#!") {
        return true;
    }
    walk_children(node, source, has_ocaml_entrypoint)
}

fn has_r_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // R scripts often have shebang
    let text = node.utf8_text(source).unwrap_or("");
    if text.starts_with("#!") {
        return true;
    }
    walk_children(node, source, has_r_entrypoint)
}

fn has_julia_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Julia: `function main()` or shebang
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("function main(") || text.starts_with("#!") {
        return true;
    }
    walk_children(node, source, has_julia_entrypoint)
}

fn has_elm_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Elm: `main =` declaration (program entrypoint)
    let text = node.utf8_text(source).unwrap_or("");
    if text.lines().any(|l| l.trim().starts_with("main "))
        || text.lines().any(|l| l.trim().starts_with("main="))
    {
        return true;
    }
    walk_children(node, source, has_elm_entrypoint)
}

fn has_nim_entrypoint(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Nim: `when isMainModule:` block (compile-time check)
    let text = node.utf8_text(source).unwrap_or("");
    if text.contains("isMainModule") && text.contains("when") {
        return true;
    }
    walk_children(node, source, has_nim_entrypoint)
}

// ── Public API surface detection ────────────────────────────────────

fn has_public_api(node: tree_sitter::Node, source: &[u8], language: Language) -> bool {
    match language {
        Language::Rust => count_pub_fns(node, source) >= 3,
        Language::Python => has_python_exports(node, source),
        Language::Go => has_go_exports(node, source),
        Language::JavaScript | Language::TypeScript => has_js_exports(node, source),
        Language::Java => has_java_public(node, source),
        Language::C | Language::Cpp => has_c_header_fns(node, source),
        Language::Ruby => has_ruby_public(node, source),
        Language::CSharp => has_csharp_public(node, source),
        Language::Kotlin => has_kotlin_public(node, source),
        Language::Php => has_php_public(node, source),
        Language::Swift => has_swift_public(node, source),
        Language::Elixir => has_elixir_public(node, source),
        Language::Haskell => has_haskell_public(node, source),
        Language::Erlang => has_erlang_public(node, source),
        Language::Scala => has_scala_public(node, source),
        Language::Zig => has_zig_public(node, source),
        Language::Lua => has_lua_public(node, source),
        Language::Dart => has_dart_public(node, source),
        Language::Clojure => has_clojure_public(node, source),
        Language::OCaml => has_ocaml_public(node, source),
        Language::R => has_r_public(node, source),
        Language::Julia => has_julia_public(node, source),
        Language::Elm => has_elm_public(node, source),
        Language::Nim => has_nim_public(node, source),
    }
}

fn count_pub_fns(node: tree_sitter::Node, source: &[u8]) -> usize {
    if node.kind() == "function_item" {
        let text = node.utf8_text(source).unwrap_or("");
        if text.starts_with("pub fn") || text.starts_with("pub async fn") {
            return 1;
        }
    }
    let children: Vec<tree_sitter::Node> = {
        let mut c = node.walk();
        node.children(&mut c).collect()
    };
    children.into_iter().map(|c| count_pub_fns(c, source)).sum()
}

fn has_python_exports(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("__all__") || text.contains("def ") || text.contains("class ")
}

fn has_go_exports(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    // Go exports are Capitalized functions/types
    let has_export = text.lines().any(|line| {
        let trimmed = line.trim();
        (trimmed.starts_with("func ") || trimmed.starts_with("type "))
            && trimmed
                .split_whitespace()
                .nth(1)
                .map(|s| s.chars().next().map(|c| c.is_uppercase()).unwrap_or(false))
                .unwrap_or(false)
    });
    has_export
}

fn has_js_exports(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("export ") || text.contains("module.exports")
}

fn has_java_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("public class") || text.contains("public interface")
}

fn has_c_header_fns(node: tree_sitter::Node, source: &[u8]) -> bool {
    // .h files with function declarations = library API
    let text = node.utf8_text(source).unwrap_or("");
    let fn_count = text.matches(");").count();
    fn_count >= 2
}

fn has_ruby_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("def ") && (text.contains("module ") || text.contains("class "))
}

fn has_csharp_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("public class")
        || text.contains("public interface")
        || text.contains("public static")
}

fn has_kotlin_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("class ") || text.contains("object ") || text.contains("fun ")
}

fn has_php_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("function ") && (text.contains("class ") || text.contains("interface "))
}

fn has_swift_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("public ")
        && (text.contains("func ") || text.contains("struct ") || text.contains("class "))
}

fn has_elixir_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Elixir: `def` (public) functions and `defmodule`
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("defmodule ") || text.contains("def ")
}

fn has_haskell_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Haskell exports: `module Foo (...) where` or top-level function definitions
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("module ") && text.contains("where")
}

fn has_erlang_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Erlang exports: `-export([func/arity, ...]).`
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("-export(")
}

fn has_scala_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Scala: class, object, trait, or def declarations
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("class ")
        || text.contains("object ")
        || text.contains("trait ")
        || text.contains("def ")
}

fn has_zig_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Zig: `pub` keyword for exported symbols
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("pub ")
}

fn has_lua_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Lua modules: functions and tables returned via `module` or `return`
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("function ") || text.contains("return ") || text.contains("local M")
}

fn has_dart_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Dart: class, function, or typedef declarations
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("class ") || text.contains("void ") || text.contains("typedef ")
}

fn has_clojure_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Clojure: `defn` (public), `defmacro`, `defrecord`, `defprotocol`
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("(defn ")
        || text.contains("(defmacro ")
        || text.contains("(defrecord ")
        || text.contains("(defprotocol ")
        || text.contains("(def ")
}

fn has_ocaml_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // OCaml: `let` declarations, `type` definitions, `module` declarations
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("let ") || text.contains("type ") || text.contains("module ")
}

fn has_r_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // R: function definitions
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("function(") || text.contains("function (") || text.contains("<- ")
}

fn has_julia_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Julia: function, struct, module declarations
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("function ")
        || text.contains("struct ")
        || text.contains("module ")
        || text.contains("const ")
}

fn has_elm_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Elm: module declaration with exposing, type/function declarations
    let text = node.utf8_text(source).unwrap_or("");
    text.contains("module ") && text.contains("exposing")
        || text.contains("type ")
        || text.contains("type alias ")
}

fn has_nim_public(node: tree_sitter::Node, source: &[u8]) -> bool {
    // Nim: exported symbols use `*` suffix (proc*, type*, var*, const*)
    let text = node.utf8_text(source).unwrap_or("");
    // Check for export markers on definitions
    text.contains("proc*")
        || text.contains("func*")
        || text.contains("type*")
        || text.contains("var*")
        || text.contains("const*")
        || text.contains("macro*")
        || text.contains("template*")
}

// ── Path-based classification ──────────────────────────────────────

fn classify_by_path(path: &str) -> GraphResult<Classification> {
    let lower = path.to_lowercase();

    if lower.contains("/example")
        || lower.contains("/examples/")
        || lower.contains("\\examples\\")
        || lower.starts_with("examples/")
        || lower.starts_with("example/")
    {
        return Ok(Classification {
            role: "example".into(),
            status: "stable".into(),
            reason: "in examples directory".into(),
            feature: None,
        });
    }

    if lower.ends_with(".toml")
        || lower.ends_with(".yaml")
        || lower.ends_with(".yml")
        || lower.ends_with(".json")
        || lower.ends_with(".lock")
        || lower.ends_with(".cfg")
        || lower.ends_with(".ini")
        || lower.ends_with(".env")
    {
        return Ok(Classification {
            role: "config".into(),
            status: "stable".into(),
            reason: "configuration file".into(),
            feature: None,
        });
    }

    if lower.contains("/scripts/") || lower.contains("\\scripts\\") {
        return Ok(Classification {
            role: "script".into(),
            status: "beta".into(),
            reason: "in scripts directory".into(),
            feature: None,
        });
    }

    Ok(Classification {
        role: "unknown".into(),
        status: "unknown".into(),
        reason: "no classification pattern matched".into(),
        feature: None,
    })
}

fn classify_library_status(path: &str) -> String {
    let lower = path.to_lowercase();
    if lower.contains("/src/") && !lower.contains("/test") && !lower.contains("/example") {
        "stable".into()
    } else {
        "beta".into()
    }
}

// ── Feature inference ────────────────────────────────────────────────

/// Infer a feature name from a file's directory structure.
///
/// ## Strategy: `directory`
///
/// Extracts the first subdirectory under `src/` or the top-level directory
/// component and derives a feature name with the `-module` or `-feature` suffix.
///
/// Examples:
/// - `src/auth/login.go` → `Some("auth-module")`
/// - `src/payments/handler.go` → `Some("payments-module")`
/// - `lib/utils.go` (no `src/`) → `Some("utils-module")`
///
/// ## Overrides
///
/// `overrides` is a map of path → feature name. Keys ending with `/` are
/// directory-prefix matches. Overrides take priority over directory inference.
/// An override value of `""` means "no feature" (returns `None`).
///
/// Returns `None` when:
/// - The strategy is invalid or unknown
/// - No directory component can be meaningfully extracted (top-level file)
/// - An override explicitly maps to `""`
pub fn infer_feature(
    path: &str,
    strategy: &str,
    overrides: Option<&std::collections::HashMap<String, String>>,
) -> Option<String> {
    // 1. Check overrides: exact match first, then directory-prefix match
    if let Some(ov) = overrides {
        // Exact match
        if let Some(feature) = ov.get(path) {
            return if feature.is_empty() {
                None
            } else {
                Some(feature.clone())
            };
        }
        // Directory-prefix match (keys ending with '/')
        for (prefix, feature) in ov {
            if prefix.ends_with('/') && path.starts_with(prefix.as_str()) {
                return if feature.is_empty() {
                    None
                } else {
                    Some(feature.clone())
                };
            }
        }
    }

    // 2. Directory-based inference
    if strategy == "directory" {
        return infer_feature_from_directory(path);
    }

    None
}

/// Extract feature name from directory structure under `src/`.
fn infer_feature_from_directory(path: &str) -> Option<String> {
    // Normalize separators
    let normalized = path.replace('\\', "/");

    // Try extraction from `src/<subdir>/...`
    // Handle both "/src/auth/..." and "src/auth/..."
    for prefix in &["/src/", "src/"] {
        if let Some(after_src) = normalized.split(prefix).nth(1) {
            let component = after_src.split('/').next().unwrap_or("");
            if !component.is_empty() {
                return Some(format!("{}-module", component));
            }
        }
    }

    // Try first meaningful directory component
    let components: Vec<&str> = normalized.split('/').filter(|c| !c.is_empty()).collect();
    match components.len() {
        0 | 1 => {
            // Top-level file — no meaningful directory structure
            None
        }
        _ => {
            // Use the first directory component
            let dir = components[0];
            // Skip hidden directories and "src" (it's handled above if there's a subdirectory)
            if dir.starts_with('.') || dir == "src" {
                None
            } else {
                Some(format!("{}-module", dir))
            }
        }
    }
}

// ── Helpers ─────────────────────────────────────────────────────────

fn walk_children(
    node: tree_sitter::Node,
    source: &[u8],
    f: fn(tree_sitter::Node, &[u8]) -> bool,
) -> bool {
    let children: Vec<tree_sitter::Node> = {
        let mut c = node.walk();
        node.children(&mut c).collect()
    };
    for child in children {
        if f(child, source) {
            return true;
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rust_entrypoint_detection() {
        let source = "fn main() {\n    println!(\"hello\");\n}\n";
        // Integration test — requires full parser setup, tested via CLI
        assert!(source.contains("fn main()"));
    }

    #[test]
    fn test_python_entrypoint_detection() {
        let source = "if __name__ == \"__main__\":\n    main()\n";
        assert!(source.contains("__main__"));
    }

    #[test]
    fn test_go_entrypoint_detection() {
        let source = "package main\n\nfunc main() {\n    fmt.Println(\"hi\")\n}\n";
        assert!(source.contains("func main()"));
    }

    #[test]
    fn test_java_entrypoint_detection() {
        let source = "public class Main {\n    public static void main(String[] args) {}\n}\n";
        assert!(source.contains("public static void main("));
    }

    #[test]
    fn test_c_entrypoint_detection() {
        let source = "int main(int argc, char **argv) {\n    return 0;\n}\n";
        assert!(source.contains("int main"));
    }

    #[test]
    fn test_test_file_detection() {
        assert!(is_test_file("src/foo_test.go"));
        assert!(is_test_file("lib/baz.test.ts"));
        assert!(is_test_file("spec/qux_spec.rb"));
        assert!(is_test_file("src/FooTest.java"));
        assert!(!is_test_file("src/main.rs"));
        assert!(!is_test_file("lib/util.py"));
    }

    #[test]
    fn test_test_file_detection_depth_agnostic() {
        // Top-level tests/ and benches/ dirs (no leading slash — GAP-036)
        assert!(is_test_file("tests/json.rs"));
        assert!(is_test_file("tests/index/basic.rs"));
        assert!(is_test_file("benches/graph_bench.rs"));
        // Nested crate-level tests/ and benches/
        assert!(is_test_file("crates/ignore/tests/gitignore_skip_bom.rs"));
        assert!(is_test_file("crates/globset/benches/bench.rs"));
        // JS __tests__ dir
        assert!(is_test_file("src/components/__tests__/button.test.tsx"));
        // Windows separators
        assert!(is_test_file("tests\\json.rs"));
        assert!(is_test_file("crates\\ignore\\tests\\gitignore_skip_bom.rs"));
        // Negative: component equality must not false-positive on test_utils/
        assert!(!is_test_file("src/test_utils.rs"));
        assert!(!is_test_file("crates/globset/src/test_util.rs"));
        assert!(!is_test_file("src/lib.rs"));
    }

    #[test]
    fn test_entrypoint_by_name() {
        assert!(is_entrypoint_by_name("src/main.rs"));
        assert!(is_entrypoint_by_name("cmd/server/main.go"));
        assert!(is_entrypoint_by_name("app/main.py"));
        assert!(is_entrypoint_by_name("src/index.js"));
        assert!(is_entrypoint_by_name("pkg/__main__.py"));
        assert!(!is_entrypoint_by_name("src/lib.rs"));
        assert!(!is_entrypoint_by_name("util/helpers.go"));
    }

    #[test]
    fn test_build_script_detection() {
        assert!(is_build_script("build.rs"));
        assert!(is_build_script("crates/foo/build.rs"));
        assert!(is_build_script("serde_derive/build.rs"));
        assert!(is_build_script("build.zig"));
        assert!(!is_build_script("src/main.rs"));
        assert!(!is_build_script("src/lib.rs"));
        assert!(!is_build_script("build.rs.bak"));
    }

    #[test]
    fn test_build_script_not_entrypoint() {
        // build.rs contains `fn main()` — must classify as "build", not entrypoint
        let result = classify_file(
            Language::Rust,
            "build.rs",
            "fn main() {\n    println!(\"build\");\n}\n",
        )
        .unwrap();
        assert_eq!(result.role, "build");
        let result =
            classify_file(Language::Rust, "crates/foo/build.rs", "fn main() {\n}\n").unwrap();
        assert_eq!(result.role, "build");
    }

    #[test]
    fn test_crate_module_root_detection() {
        assert!(is_crate_module_root("src/lib.rs"));
        assert!(is_crate_module_root("serde_core/src/lib.rs"));
        assert!(is_crate_module_root("src/de/mod.rs"));
        assert!(is_crate_module_root("src/mod.rs"));
        assert!(!is_crate_module_root("src/main.rs"));
        assert!(!is_crate_module_root("src/de/mod2.rs"));
        assert!(!is_crate_module_root("build.rs"));
    }

    #[test]
    fn test_crate_root_classifies_library() {
        // Macro/re-export wall lib.rs (serde-style) — no pub fns, no entrypoint
        let source = "#[macro_export]\nmacro_rules! my_macro {\n    () => {};\n}\npub use core::Serialize;\n";
        let result = classify_file(Language::Rust, "serde/src/lib.rs", source).unwrap();
        assert_eq!(result.role, "library");
        // Nested module root
        let result =
            classify_file(Language::Rust, "serde/src/de/mod.rs", "pub mod value;\n").unwrap();
        assert_eq!(result.role, "library");
        // Entrypoint by name still wins
        let result = classify_file(Language::Rust, "src/main.rs", "fn main() {}\n").unwrap();
        assert_eq!(result.role, "entrypoint");
    }

    #[test]
    fn test_path_based_example() {
        let result = classify_by_path("examples/hello.rs").unwrap();
        assert_eq!(result.role, "example");
    }

    #[test]
    fn test_rust_pub_fn_count() {
        let source = "pub fn foo() {}\npub fn bar() {}\npub async fn baz() {}\nfn private() {}\n";
        assert!(source.matches("pub fn").count() + source.matches("pub async fn").count() >= 3);
    }

    #[test]
    fn test_python_exports_detection() {
        let source = "__all__ = [\"Foo\", \"Bar\"]\n\ndef foo():\n    pass\n";
        assert!(source.contains("__all__"));
    }

    #[test]
    fn test_js_exports_detection() {
        assert!("export function foo() {}".contains("export "));
        assert!("module.exports = { foo }".contains("module.exports"));
    }

    #[test]
    fn test_path_based_config() {
        let result = classify_by_path("Cargo.toml").unwrap();
        assert_eq!(result.role, "config");
        let result = classify_by_path(".github/workflows/ci.yaml").unwrap();
        assert_eq!(result.role, "config");
    }

    // ── Generated file detection tests ──────────────────────────────

    #[test]
    fn test_generated_path_patterns() {
        assert!(is_generated_file("api/user.pb.go", b""));
        assert!(is_generated_file("pkg/models.gen.go", b""));
        assert!(is_generated_file("src/types.generated.ts", b""));
        assert!(is_generated_file("lib/models.generated.py", b""));
    }

    #[test]
    fn test_generated_header_markers() {
        assert!(is_generated_file(
            "src/types.go",
            b"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n"
        ));
        assert!(is_generated_file(
            "lib/models.py",
            b"# auto-generated -- do not modify\n"
        ));
        assert!(is_generated_file(
            "pkg/types.rs",
            b"// DO NOT EDIT -- this file is auto-generated\n"
        ));
    }

    #[test]
    fn test_non_generated_files() {
        assert!(!is_generated_file(
            "src/main.go",
            b"package main\n\nfunc main() {\n"
        ));
        assert!(!is_generated_file(
            "lib/util.py",
            b"def foo():\n    return 42\n"
        ));
        assert!(!is_generated_file(
            "src/lib.rs",
            b"pub fn add(a: i32, b: i32) -> i32 { a + b }\n"
        ));
    }

    #[test]
    fn test_generated_classification() {
        // Path pattern — should classify as generated before reaching test/lib checks
        let result = classify_file(Language::Go, "api/user.pb.go", "").unwrap();
        assert_eq!(result.role, "generated");
        assert_eq!(result.status, "generated");

        // Header marker
        let result = classify_file(
            Language::Python,
            "models/types.py",
            "# auto-generated by script\nclass Foo: pass\n",
        )
        .unwrap();
        assert_eq!(result.role, "generated");
    }

    #[test]
    fn test_generated_takes_priority_over_test() {
        // A file that matches BOTH test and generated patterns should be classified as generated
        let result = classify_file(Language::Go, "api/user_test.gen.go", "").unwrap();
        assert_eq!(result.role, "generated");
    }

    // ── Feature inference tests ──────────────────────────────────────

    #[test]
    fn test_feature_inference_directory_src_subdir() {
        // src/auth/login.go → auth-module
        let feature = infer_feature("src/auth/login.go", "directory", None);
        assert_eq!(feature.as_deref(), Some("auth-module"));
    }

    #[test]
    fn test_feature_inference_directory_src_deep() {
        // src/payments/internal/handler.go → payments-module
        let feature = infer_feature("src/payments/internal/handler.go", "directory", None);
        assert_eq!(feature.as_deref(), Some("payments-module"));
    }

    #[test]
    fn test_feature_inference_no_src_dir() {
        // lib/utils.go (no src/) → first component
        let feature = infer_feature("lib/utils.go", "directory", None);
        assert_eq!(feature.as_deref(), Some("lib-module"));
    }

    #[test]
    fn test_feature_inference_top_level_file() {
        // README.md at root → no feature
        let feature = infer_feature("README.md", "directory", None);
        assert_eq!(feature, None);
    }

    #[test]
    fn test_feature_inference_hidden_dir() {
        // .github/workflows/ci.yaml → skip hidden dirs
        let feature = infer_feature(".github/workflows/ci.yaml", "directory", None);
        assert_eq!(feature, None);
    }

    #[test]
    fn test_feature_inference_disabled() {
        // Unknown/invalid strategy → no feature
        let feature = infer_feature("src/auth/login.go", "none", None);
        assert_eq!(feature, None);
    }

    #[test]
    fn test_feature_inference_override_exact() {
        let mut overrides = std::collections::HashMap::new();
        overrides.insert("src/auth/login.go".to_string(), "auth-service".to_string());
        let feature = infer_feature("src/auth/login.go", "directory", Some(&overrides));
        assert_eq!(feature.as_deref(), Some("auth-service"));
    }

    #[test]
    fn test_feature_inference_override_directory_prefix() {
        let mut overrides = std::collections::HashMap::new();
        overrides.insert("src/auth/".to_string(), "authentication".to_string());
        // File under src/auth/ → matches directory prefix
        let feature = infer_feature("src/auth/login.go", "directory", Some(&overrides));
        assert_eq!(feature.as_deref(), Some("authentication"));

        // File NOT under src/auth/ → falls through to directory inference
        let feature = infer_feature("src/payments/handler.rs", "directory", Some(&overrides));
        assert_eq!(feature.as_deref(), Some("payments-module"));
    }

    #[test]
    fn test_feature_inference_override_empty() {
        let mut overrides = std::collections::HashMap::new();
        overrides.insert("src/vendor/".to_string(), "".to_string());
        // Empty override → no feature
        let feature = infer_feature("src/vendor/lib.go", "directory", Some(&overrides));
        assert_eq!(feature, None);
    }

    #[test]
    fn test_feature_inference_windows_separators() {
        let feature = infer_feature("src\\auth\\login.go", "directory", None);
        assert_eq!(feature.as_deref(), Some("auth-module"));
    }

    // ── GAP-099: entry-symbol extraction ─────────────────────────────

    #[test]
    fn test_entry_symbols_rust_pub_fns() {
        let source = "pub struct Engine;\n\n/// Builds the engine.\npub fn new() -> Engine { Engine }\n\nfn helper() {}\n\npub fn run(&self) {}\n";
        let symbols = extract_entry_symbols(Language::Rust, source);
        assert!(
            symbols.contains(&"new".to_string()),
            "pub fn new missing: {symbols:?}"
        );
        assert!(
            symbols.contains(&"run".to_string()),
            "pub fn run missing: {symbols:?}"
        );
        assert!(
            !symbols.contains(&"helper".to_string()),
            "private fn must not appear: {symbols:?}"
        );
    }

    #[test]
    fn test_entry_symbols_rust_nested_not_top_level() {
        // A pub fn inside an impl block is not a top-level entry symbol.
        let source = "struct E;\nimpl E {\n    pub fn build() -> E { E }\n}\npub fn top() {}\n";
        let symbols = extract_entry_symbols(Language::Rust, source);
        assert_eq!(
            symbols,
            vec!["top".to_string()],
            "impl-block fn leaked: {symbols:?}"
        );
    }

    #[test]
    fn test_entry_symbols_python_top_level_defs_and_classes() {
        let source = "import os\n\n\nclass Flask:\n    def __init__(self):\n        pass\n\n    def nested(self):\n        pass\n\n\ndef create_app():\n    return Flask()\n\n\ndef _private():\n    pass\n";
        let symbols = extract_entry_symbols(Language::Python, source);
        assert!(
            symbols.contains(&"Flask".to_string()),
            "class Flask missing: {symbols:?}"
        );
        assert!(
            symbols.contains(&"create_app".to_string()),
            "top-level def missing: {symbols:?}"
        );
        assert!(
            !symbols.contains(&"nested".to_string()),
            "method must not appear: {symbols:?}"
        );
        // _private IS a top-level def: it counts (agents may call it).
        assert!(symbols.contains(&"_private".to_string()));
    }

    #[test]
    fn test_entry_symbols_go_exported_first_with_methods() {
        let source = "package gin\n\nfunc New() *Engine { return nil }\n\nfunc internal() {}\n\ntype Engine struct{}\n\nfunc (e *Engine) Run(addr string) error { return nil }\n\nfunc Default() *Engine { return nil }\n\nfunc hidden() {}\n";
        let symbols = extract_entry_symbols(Language::Go, source);
        // Exported first (New, Default, Run — canonical names lead), then unexported.
        let exported_idx = |n: &str| symbols.iter().position(|s| s == n).unwrap_or(usize::MAX);
        assert!(
            exported_idx("New") < exported_idx("Default")
                && exported_idx("Default") < exported_idx("Run"),
            "canonical order wrong: {symbols:?}"
        );
        assert!(
            exported_idx("Run") < exported_idx("internal"),
            "exported must precede unexported: {symbols:?}"
        );
        assert!(
            symbols.contains(&"internal".to_string()),
            "unexported func missing: {symbols:?}"
        );
        assert!(
            symbols.contains(&"hidden".to_string()),
            "unexported hidden missing: {symbols:?}"
        );
    }

    #[test]
    fn test_entry_symbols_unsupported_language_empty() {
        let symbols = extract_entry_symbols(Language::Ruby, "def main\nend\n");
        assert!(symbols.is_empty());
    }

    #[test]
    fn test_entry_symbols_pattern_seeded_go_main() {
        // A Go main package: entrypoint via AST pattern, seed is func main().
        let source = "package main\n\nfunc main() {\n    run()\n}\n\nfunc run() {}\n";
        let symbols =
            entry_symbols_for_classification(Language::Go, "contains entrypoint pattern", source);
        // The seed matched: symbols after the seed line survive (run is at line 6).
        assert!(
            symbols.contains(&"run".to_string()),
            "post-seed symbol missing: {symbols:?}"
        );
    }

    #[test]
    fn test_entry_symbols_guard_body_wrapper_target() {
        // flask cli.py shape: main() is invoked inside the __main__ guard
        // but defined BEFORE it — the report must still name it.
        let source = "def main():\n    pass\n\n\nif __name__ == \"__main__\":\n    main()\n";
        let symbols = entry_symbols_for_classification(
            Language::Python,
            "contains entrypoint pattern for Python",
            source,
        );
        assert!(
            symbols.contains(&"main".to_string()),
            "guard-invoked wrapper target missing: {symbols:?}"
        );
        assert!(
            symbols
                .iter()
                .any(|s| s.starts_with('<') && s.ends_with('>')),
            "seed marker missing: {symbols:?}"
        );
    }

    #[test]
    fn test_classification_canonical_go_entry_constructors() {
        // A gin-style library file that declares the canonical entry
        // constructors (New/Default) plus a Run method is an entrypoint,
        // not a library — its constructors ARE where execution starts.
        let source = "package gin\n\ntype Engine struct{}\n\nfunc New() *Engine { return nil }\n\nfunc Default() *Engine { return nil }\n\nfunc (e *Engine) Run(addr string) error { return nil }\n\nfunc (e *Engine) internal() {}\n";
        let c = classify_file(Language::Go, "gin.go", source).unwrap();
        assert_eq!(c.role, "entrypoint", "reason: {}", c.reason);
        assert!(c.reason.contains("canonical entry"), "reason: {}", c.reason);
    }

    #[test]
    fn test_classification_canonical_go_needs_run_method_or_default() {
        // func New() alone (a common constructor) is NOT enough — gin.go's
        // surface is New+Default+Run; a lone constructor stays a library.
        let source = "package pkg\n\nfunc New() *Thing { return nil }\n";
        let c = classify_file(Language::Go, "thing.go", source).unwrap();
        assert_ne!(c.role, "entrypoint", "reason: {}", c.reason);
    }

    #[test]
    fn test_classification_canonical_python_flask_class() {
        // A file declaring `class Flask` is the framework's entrypoint —
        // the class is where an application starts (GAP-099 flask case).
        let source = "class Flask:\n    def __init__(self, import_name):\n        pass\n\n    def run(self):\n        pass\n";
        let c = classify_file(Language::Python, "app.py", source).unwrap();
        assert_eq!(c.role, "entrypoint", "reason: {}", c.reason);
        assert!(c.reason.contains("canonical entry"), "reason: {}", c.reason);
    }

    #[test]
    fn test_classification_canonical_python_other_class_not_entrypoint() {
        // An arbitrary class (not a canonical entry class) stays a library.
        let source = "class Widget:\n    def __init__(self):\n        pass\n\n    def run(self):\n        pass\n";
        let c = classify_file(Language::Python, "widget.py", source).unwrap();
        assert_ne!(c.role, "entrypoint", "reason: {}", c.reason);
    }

    #[test]
    fn test_classification_canonical_rust_untouched() {
        // Rust files keep the existing classification: top-level pub fns
        // are library surface, not canonical entry constructors.
        let source = "pub fn new() -> u32 { 0 }\npub fn run() {}\npub fn a() {}\n";
        let c = classify_file(Language::Rust, "lib.rs", source).unwrap();
        assert_eq!(c.role, "library", "reason: {}", c.reason);
    }

    #[test]
    fn test_entry_symbols_filename_convention_reports_all() {
        // main.rs by filename convention: all pub fns report as-is.
        let source = "pub fn setup() {}\nfn main() {}\n";
        let symbols =
            entry_symbols_for_classification(Language::Rust, "filename convention", source);
        assert!(symbols.contains(&"setup".to_string()), "{symbols:?}");
        assert!(symbols.contains(&"main".to_string()), "{symbols:?}");
    }

    #[test]
    fn test_classification_classification_entrypoint_python_seed_marker() {
        // Python file with only a __main__ guard: the guard-invoked target
        // (`run`, defined before the guard) is named, plus the seed marker
        // documenting the pattern itself.
        let source = "def run():\n    pass\n\n\nif __name__ == \"__main__\":\n    run()\n";
        let symbols = entry_symbols_for_classification(
            Language::Python,
            "contains entrypoint pattern for Python",
            source,
        );
        assert_eq!(
            symbols,
            vec![
                "run".to_string(),
                "<if __name__ == \"__main__\">".to_string()
            ],
            "{symbols:?}"
        );
    }
}
